name: Refresh Update_Site

on:
  workflow_dispatch:

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven Tycho
        run: mvn -B clean verify -ntp -DskipTests

      - name: Copy update site content to update_site/
        run: |
          rm -rf update_site/*
          cp -r $(find sites -type d -path 'sites/*/target/repository' | head -n 1)/* update_site/
        # 当前只支持最新版本，要支持历史版本需要保留完整的p2 repository
        #   cp -rf $(find sites -type d -path 'sites/*/target/repository' | head -n 1)/* update_site/

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global push.autoSetupRemote true

      - name: Check for changes
        id: changes
        run: |
          changed=$(git status --porcelain update_site | wc -l)
          echo "changed=$changed" >> "$GITHUB_OUTPUT"

      - name: Push changes if update_site changed
        if: steps.changes.outputs.changed != '0'
        run: |
          git add -A update_site
          git commit -m "build: Update update_site with latest build artifacts"

      - name: Create Pull Request
        if: steps.changes.outputs.changed != '0'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update update_site with latest build artifacts
          branch: 'update-site-update'
          title: "build: Update update_site directory with latest build artifacts"
          body: |
            This PR updates the update_site directory with the latest build artifacts generated by Tycho build.
          base: master